.. |icon_allDTV| image:: ../../../resources/VizIcons/allDTV.ico
.. |icon_Figure| image:: ../../../resources/VizIcons/Figure.ico
.. |icon_minus3x| image:: ../../../resources/VizIcons/minus3x.ico
.. |icon_minus| image:: ../../../resources/VizIcons/minus.ico
.. |icon_new| image:: ../../../resources/VizIcons/new.ico
.. |icon_plotMultiple| image:: ../../../resources/VizIcons/plotMultiple.ico
.. |icon_plotSingle| image:: ../../../resources/VizIcons/plotSingle.ico
.. |icon_plus3x| image:: ../../../resources/VizIcons/plus3x.ico
.. |icon_plus| image:: ../../../resources/VizIcons/plus.ico
.. |icon_showHide| image:: ../../../resources/VizIcons/showHide.ico
.. |icon_StackedPlotView| image:: ../../../resources/VizIcons/StackedPlotView.ico
.. |icon_TablePlotView| image:: ../../../resources/VizIcons/TablePlotView.ico
.. |icon_thisDTV| image:: ../../../resources/VizIcons/thisDTV.ico

