.. |icon_allDTV| image:: ../../../resources/VizIcons/allDTV.png
  :width: 15px
  :height: 15px

.. |icon_Figure| image:: ../../../resources/VizIcons/Figure.png
  :width: 15px
  :height: 15px

.. |icon_minus3x| image:: ../../../resources/VizIcons/minus3x.png
  :width: 15px
  :height: 15px

.. |icon_minus| image:: ../../../resources/VizIcons/minus.png
  :width: 15px
  :height: 15px

.. |icon_new| image:: ../../../resources/VizIcons/new.png
  :width: 15px
  :height: 15px

.. |icon_plotMultiple| image:: ../../../resources/VizIcons/plotMultiple.png
  :width: 15px
  :height: 15px

.. |icon_plotSingle| image:: ../../../resources/VizIcons/plotSingle.png
  :width: 15px
  :height: 15px

.. |icon_plus3x| image:: ../../../resources/VizIcons/plus3x.png
  :width: 15px
  :height: 15px

.. |icon_plus| image:: ../../../resources/VizIcons/plus.png
  :width: 15px
  :height: 15px

.. |icon_showHide| image:: ../../../resources/VizIcons/showHide.png
  :width: 15px
  :height: 15px

.. |icon_StackedPlotView| image:: ../../../resources/VizIcons/StackedPlotView.png
  :width: 15px
  :height: 15px

.. |icon_TablePlotView| image:: ../../../resources/VizIcons/TablePlotView.png
  :width: 15px
  :height: 15px

.. |icon_thisDTV| image:: ../../../resources/VizIcons/thisDTV.png
  :width: 15px
  :height: 15px


